      - name: Configurar Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: 'platform-tools'

      - name: Instalar Android SDK 35
        run: sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'
